<?php

namespace Mairie\MairieBundle\Repository;

/**
 * Acte_de_naissanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Acte_de_naissanceRepository extends \Doctrine\ORM\EntityRepository
{
}
