<?php

namespace Mairie\MairieBundle\Repository;

/**
 * communeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class communeRepository extends \Doctrine\ORM\EntityRepository
{
}
