<?php

namespace Mairie\MairieBundle\Repository;

/**
 * DecesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecesRepository extends \Doctrine\ORM\EntityRepository
{
}
