<?php

namespace Mairie\MairieBundle\Repository;

/**
 * Etat_civilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etat_civilRepository extends \Doctrine\ORM\EntityRepository
{
}
