<?php

namespace Mairie\MairieBundle\Repository;

/**
 * MariageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MariageRepository extends \Doctrine\ORM\EntityRepository
{
}
