<?php

namespace Mairie\MairieBundle\Repository;

/**
 * NaissanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NaissanceRepository extends \Doctrine\ORM\EntityRepository
{
}
