mairie_mairie:
    resource: "@MairieMairieBundle/Controller/"
    type:     annotation
    prefix:   /mairie

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login_check:
    path:   /secured_area/login_check
     
logout:
    path:   /secured_area/logout