# app/config/security.yml
security:
    providers:
        
            database_users:
            entity: { class: Mairie\MairieBundle:Admin, property: username }
        
    encoders:
        Mairie\MairieBundle\Entity\Admin: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]       
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: security.providers.database_users
        
        secured_area:
            pattern:  ^/
            anonymous: ~
            form_login:
               login_path:  login
               check_path:  login_check
               use_referer: true
            logout:
               path: /logout
               target: /
    access_control:
      
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_USER }       