# app/config/security.yml
security:
    providers:
        database_users:
            entity: { class: Mairie\MairieBundle:Admin, property: username }
       
    encoders:
        Mairie\MairieBundle\Entity\Admin: bcrypt
           
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/demo/secured/login$
            security: false
        secured_area:
            pattern:  ^/
            anonymous: ~
            form_login:
               login_path:  login
               check_path:  login_check
               use_referer: true
            logout:
               path: /logout
               target: /
    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       #- { path: ^/mairie, roles: ROLE_ADMIN }