# app/config/security.yml
security:
    providers:
        in_memory:
            memory:
                users:
                    username:
                        password: $2y$12$UMRq6nCYrRMVfVoMGdqjQ.jbPgrIvlFYBUy20BKfx6.xuAiAF9ssi
                        roles: ROLE_USER
                    test:
                        password: $2y$12$UMRq6nCYrRMVfVoMGdqjQ.jbPgrIvlFYBUy20BKfx6.xuAiAF9ssi
                        roles: ROLE_ADMIN
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/demo/secured/login$
            security: false
        secured_area:
            pattern:  ^/
            anonymous: ~
            form_login:
               login_path:  login
               check_path:  login_check
               use_referer: true
            logout:
               path: /logout
               target: /
    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       #- { path: ^/mairie, roles: ROLE_ADMIN }