# app/config/security.yml
security:
    providers:
        in_memory: { memory: ~ }
        database_users:
            entity: { class: Mairie\MairieBundle:Admin, property: username }
        
    encoders:
        Mairie\MairieBundle\Entity\Admin: bcrypt
           
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main: 
            anonymous: ~
                
        
            form_login:
               login_path: security_login_check
               check_path: security_login_form
            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: homepage
      
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_USER }       